### PR TITLE
Update preview chart values to only have 1 replica

### PR DESCRIPTION
**Pull request by vanetix**

### CODE REVIEW

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by chaseconey** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by vanetix** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Comment by vanetix** [comment]
:star: PR built and available in a preview environment **vanetix-slacker-pr-2** [here](http://jx-vanetix-slacker-pr-2-preview.jx-vanetix-slacker-pr-2.jx.k8s.ccards.io)

**Pull request merged**
